### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by fredhampton**

### CODE REVIEW

**Comment by pfrazee** [comment]
Hey @fredhampton did you mean to create this PR? The `develop` branch is where I make changes that aren't quite ready to be put in `master`

**Comment by fredhampton** [comment]
I made a mistake….please disregard my PR 




 

On September 12, 2016 at 10:48:26 AM, Paul Frazee (notifications@github.com) wrote:

Hey @fredhampton did you mean to create this PR? The develop branch is where I make changes that aren't quite ready to be put in master

**Comment by pfrazee** [comment]
No worries!

**Comment by pfrazee** [comment]
How's everything going with the browser? Any recent issues or requests?

**Comment by fredhampton** [comment]
going great with the beaker !!!
we want to add a link to our bookmarklet tool on the tool bar 
is this possible 

 

On September 12, 2016 at 11:03:12 AM, Paul Frazee (notifications@github.com) wrote:

How's everything going with the browser? Any recent issues or requests?

**Comment by pfrazee** [comment]
Could you show me the bookmarklet? (I just need to confirm that I know what
you're referring to)

**Comment by fredhampton** [comment]
We use this https://getpocket.com/add/

 

On September 12, 2016 at 7:03:31 PM, Paul Frazee (notifications@github.com) wrote:

Could you show me the bookmarklet? (I just need to confirm that I know what
you're referring to)

**Comment by pfrazee** [comment]
Gotcha! I can put the tools you need on the roadmap.

**Comment by fredhampton** [comment]
Thanks !

 

On September 13, 2016 at 6:36:52 AM, Paul Frazee (notifications@github.com) wrote:

Gotcha! I can put the tools you need on the roadmap.

**Pull request closed without merging**
